# Generated by Django 4.0.2 on 2022-02-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor_email_proveedor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
