# Generated by Django 4.0.2 on 2022-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_proveedor_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='last_login',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='username',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
